
-- Eliminar base de datos comerciodb si existe
DROP DATABASE IF EXISTS comerciodb;

-- crear Base de datos comerciodb
CREATE DATABASE comerciodb;

-- Establer base de datos comerciodb
USE comerciodb;

-- Crear tabla usuario
DROP TABLE IF EXISTS TBL_USER;
CREATE TABLE TBL_USER (
    ID_USER INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(45) NOT NULL UNIQUE,
    PASSWORD VARCHAR(128) NOT NULL,
    ENABLED TINYINT(1) NOT NULL DEFAULT 1
);

-- Crear tabla rol
DROP TABLE IF EXISTS TBL_ROL;
CREATE TABLE TBL_ROL (
    ID_ROL INT PRIMARY KEY AUTO_INCREMENT,
    ROL VARCHAR(45) NOT NULL,
    ID_USER INT NOT NULL,
    CONSTRAINT USER_ROL_UNIQUE UNIQUE (ROL, ID_USER),
    CONSTRAINT FK_USER_ROL FOREIGN KEY (ID_USER)
    REFERENCES TBL_USER(ID_USER)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

-- Crear tabla continente
DROP TABLE IF EXISTS TBL_CONTINENTE;
CREATE TABLE TBL_CONTINENTE
(
	ID_CONTINENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOM_CONTINENTE VARCHAR(100)
);

-- crear tabla país
DROP TABLE IF EXISTS TBL_PAIS;
CREATE TABLE TBL_PAIS
(
	ID_PAIS INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOM_PAIS VARCHAR(80) NOT NULL,
    ID_CONTINENTE INT NOT NULL,
    CONSTRAINT CONTINENTE_PAIS FOREIGN KEY (ID_CONTINENTE)
    REFERENCES TBL_CONTINENTE(ID_CONTINENTE)
    
);

-- Crear tabla Sucursal
DROP TABLE IF EXISTS TBL_SUCURSAL;
CREATE TABLE TBL_SUCURSAL
(
	ID_SUCURSAL INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOM_SUCURSAL VARCHAR(80) NOT NULL,
    ID_PAIS INT NOT NULL,
	CONSTRAINT PAIS_SURCURSAL FOREIGN KEY (ID_PAIS)
    REFERENCES TBL_PAIS(ID_PAIS)
);

-- Insertar Usuarios
INSERT INTO TBL_USER(USERNAME, PASSWORD) VALUES ('admin','$2a$10$92xaOlTdsCVTnqPZc6kaOu23OCD8cccqoFRAI2wmaOAB7/s2NFCzK');
INSERT INTO TBL_USER(USERNAME, PASSWORD) VALUES ('user', '$2a$10$qsYg85VmnEHqV97lpFIx3.B/02diqdLfehCsDK/u5IqY3ACE5Mijy');

-- Insertar Roles
INSERT INTO TBL_ROL(ROL, ID_USER) VALUES ('ROLE_ADMIN',1);
INSERT INTO TBL_ROL(ROL, ID_USER) VALUES ('ROLE_USER',1);
INSERT INTO TBL_ROL(ROL, ID_USER) VALUES ('ROLE_USER',2);

-- Insertar continenes
INSERT INTO TBL_CONTINENTE (NOM_CONTINENTE) VALUES ('Europa');
INSERT INTO TBL_CONTINENTE (NOM_CONTINENTE) VALUES ('África');
INSERT INTO TBL_CONTINENTE (NOM_CONTINENTE) VALUES ('America');
INSERT INTO TBL_CONTINENTE (NOM_CONTINENTE) VALUES ('Asia');
INSERT INTO TBL_CONTINENTE (NOM_CONTINENTE) VALUES ('Oceanía');

-- Insertar Paises
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Albania',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Andorra ',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Bosnia y herzegovina',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Croacia',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Eslovenia',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('España',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Grecia',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Italia',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Macedonia',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Malta',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Montenegro',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Portugal',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('San Marino',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Santa Sede',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Serbia',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Alemania',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Austria',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Belga',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Francia',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Luxemburgo',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Mónaco',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Paises Bajos',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Suiza',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Belarús',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Bulgaria',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Hungría',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Moldavia',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Polonia',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Republica checa',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('República Eslovaca',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Rumania',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Rusia',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Ucrania',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Dinamarca',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Finlandia',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Irlanda',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Islandia',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Letonia',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Lituania',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Noruega',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Reino unido',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Suecia',1);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Angola',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Camerún',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Congo',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Gabón',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Guinea Ecuatorial',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('República Centroafricana',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('República Democrática del Congo',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Santo Tomé y Príncipe',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Chad',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Lesoto',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Namibia',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Sudáfrica',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Suazilandia',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Benín',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Burkina Faso',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Cabo Verde',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Costa de Marfil',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Gambia',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Ghana',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Guinea-Bisáu',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Liberia',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Malí',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Mauritania',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Níger',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Nigeria',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Senegal',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Sierra leona',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Ir',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Burundi',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Comoras',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Yibuti',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Eritrea',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Etiopía',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Kenia',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Madagascar',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Malaui',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Mozambique',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Ruanda',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Seychelles',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Somalia',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Tanzania',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Uganda',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Zambia',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Zimbabue',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Argelia',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Egipto',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Libia',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Marruecos',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Sáhara Occidental',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Sudán del Sur',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Sudán',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Túnez ',2);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('belice',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Costa Rica',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('El Salvador',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Guatemala',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Honduras',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('México',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Nicaragua',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Panamá',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Canadá',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Estados Unidos de America',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Argentina',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Bolivia',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Brasil',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Colombia',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Ecuador',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Guayana',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Perú',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Surinam ',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Uruguay',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Venezuela',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Chile',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Antigua y Barbuda',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Bahamas',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Barbados',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Cuba',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Dominica',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Granada',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Haití',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Jamaica',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('República Dominicana',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('San Cristóbal y Nieves',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Santa Lucía',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('San Vicente y las Granadinas',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Trinidad y tobago',3);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Kazajstán',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Kirguistán',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Tadyikistán',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Turkmenistán',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Uzbekistán',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Afganistan',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Bangladesh',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Bután',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('India',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Irán',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Maldivas',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Nepal',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Pakistán',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Sri Lanka',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Arabia Saudí',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Armenia ',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Azerbaiyán',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Bahréin',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Emiratos árabes unidos',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Georgia',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Yemen',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Irak',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Israel',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Jordania',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Kuwait',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Omán',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Katar',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Siria',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Palestina)',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Turquía',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Chipre',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Corea del Norte',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('corea del sur',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Japon',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Mongolia',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('China',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Porcelana',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Brunéi',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Camboya',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Filipinas',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Indonesia',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Laos',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('malasia',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Birmania',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Singapur',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Tailandia',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Timor oriental',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Vietnam',4);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Australia',5);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Nueva Zelanda',5);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Fiyi',5);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Islas Salomón',5);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Papúa Nueva Guinea',5);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Vanuatu',5);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Islas Marshall',5);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Kiribati',5);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Micronesia',5);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Nauru',5);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Palaos',5);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Samoa',5);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Tonga',5);
INSERT INTO TBL_PAIS (NOM_PAIS, ID_CONTINENTE) VALUES ('Tuvalu',5);

