DROP TABLE IF EXISTS TBL_USER;
CREATE TABLE TBL_USER (
    ID_USER INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(45) NOT NULL UNIQUE,
    PASSWORD VARCHAR(128) NOT NULL,
    ENABLED TINYINT(1) NOT NULL DEFAULT 1
);
DROP TABLE IF EXISTS TBL_ROL;
CREATE TABLE TBL_ROL (
    ID_ROL INT PRIMARY KEY AUTO_INCREMENT,
    ROL VARCHAR(45) NOT NULL,
    ID_USER INT NOT NULL,
    CONSTRAINT USER_ROL_UNIQUE UNIQUE (ROL, ID_USER),
    CONSTRAINT FK_USER_ROL FOREIGN KEY (ID_USER)
    REFERENCES TBL_USER(ID_USER)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
DROP TABLE IF EXISTS TBL_CONTINENTE;
CREATE TABLE TBL_CONTINENTE
(
	ID_CONTINENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOM_CONTINENTE VARCHAR(100)
);
DROP TABLE IF EXISTS TBL_PAIS;
CREATE TABLE TBL_PAIS
(
	ID_PAIS INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOM_PAIS VARCHAR(80) NOT NULL,
    ID_CONTINENTE INT NOT NULL,
    CONSTRAINT CONTINENTE_PAIS FOREIGN KEY (ID_CONTINENTE)
    REFERENCES TBL_CONTINENTE(ID_CONTINENTE)
);
DROP TABLE IF EXISTS TBL_SUCURSAL;
CREATE TABLE TBL_SUCURSAL
(
	ID_SUCURSAL INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOM_SUCURSAL VARCHAR(80) NOT NULL,
    ID_PAIS INT NOT NULL,
	CONSTRAINT PAIS_SURCURSAL FOREIGN KEY (ID_PAIS)
    REFERENCES TBL_PAIS(ID_PAIS)
);